language: ruby
rvm:
- 2.3.1
env:
  matrix:
  - DB=postgresql
  global:
  - secure: gqcFmn52+n+pUk9gpvjIui6cazScaTdxINh+X5RKjLYE8fksjKKlgvevUKZA6za+VoB9ZHt3/nrfBIvMT6ygBWhNkntXB3VAlEAjXPf37BJGkmzdbzAh+34lMKQCGTdVIvHfGPbXs/pb8enT4AhkRXVfQ3K+5fjDkea4NdgnXAesNSmrCDT9pIZkew61KGqsSO55yrhvKNQ9fyaX9+bCNTdI+0szjEQSlMcfS/VgZN+VwaFLqwIGZdkoY+NpkuYrTMxKbnCePUzeWYEyRqkxP2NOqkVajZLoMHNN9lBsWmZah21z4A1eDEkirrEw6hkNd2uq5DIeqnsah3mefjv2WwOiitIEftezkjv5Nqu6ljlhMYCqU1W59ec5XV3+atnTCtGDWTlbNW73oxxG8Ea2HgFOz5mGKhdAXcrxCDVNquu+7vj8wZ9bQz77GswFrx1vQbngfnt0Io2P9LpXiVprK4RB2EirQj/5aHpA7YcCSDW9UVzda7lQkp71vXt2Uu3fA8T2KTBL927k8tnnupBtCUDanls7b00DuGU+CmErelzSAMb6mRcKZW+oNvALW53sVEkS9ynys/tRtb8uIV8LZcbbmQgM5kbOUmi4JXNXIoaQpQiHqtm9qj3hKBGAqk/cIYN8nIODkH2QQnQfrhe9NdUg5UNEiXN20lRKxVVUgl0=
  - secure: HFPKDM4+QXP4sIxeXa/2OQ9sj0IxptUTogAleDCCJahVy0ADnfWlNWgDgeRI0PGv5n5IDxjWdh0cxAaRLf7e6Zn6n9Ho+dT8qW4y/4gzwUoaS/sRFiQw7sPjcCi8pqf1aB4fCZBk4JawMNmlyfYyBaiVmB0/UkGrsNUGiFMYGiAPcGt6UlSF+nxeJ9LqUTr2cDEuBJbFToAYpWeGMUoKNkkVXqOtGTkBcajF3xWHBxxdzFNUx1BQstdpZzS3Yl95BblivGA6yLxAxSr0RyF/egrgSPv5vdw/DNEcBOdzATFwriIvhrdQBM1fsJyxDeHiUcj5vD2pKXKAHMADtH3FiGi6mDspuhwe3utOsuE11A08FptEeaHpyzCQONsbxmm3FLfbv5QE//jHSxW7Zk3lVUjje6Jh97bj23z1wsaDwbU2WgUOFW+Bw+CXsml5wAmZErXcItcTSdrWpFPX3FreTO5IlFWbrsYyCWG2vljBDLTjOQzCEZ6vtU8TNqlOIvLVruTju+xR4CVPjNEvBRLFUKziVDE8d8KSqIsU56wUcpCGJGYN1BRxAU0pb1hWqUMPgr65yemrnVDY3hCKoLA7FXGQgivL8vy+PPGukAV7QaUsv4VUKJxYvQyDiK2YIm7ki9xiSA1fc156bXe6dXIbC9SA+aVU85WYWzOb0PKs9Dk=
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database mkdevnext_test' -U postgres
